[project]
name = "fin-model-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "numpy",
    "openpyxl",
    "pypdf",
    "beautifulsoup4",
    "lxml",
    "requests",
    "yfinance",
    "scipy",
    "langchain>=1.3.17",
    "langchain-community>=0.4.2",
    "rich>=15.0.0",
    "langchain-mistralai>=1.1.6",
    "langchain-groq>=1.1.3",
]
